sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Cyf2023!
  #阿里云OSS
  alioss:
    endpoint:        https://oss-cn-guangzhou.aliyuncs.com
    accessKeyId:     LTAI5tFXBNFpG9PHtETad4kx
    accessKeySecret: dvwQRBVHsRQFQt8cRB
    bucketName:      web-cyf-tlias